### ISSUE TITLE
Deserves its own NuGet package...

### ISSUE THREAD

**Issue by 9DigitNumber** [sitebro/Avo-AspNet-Identity-MongoDB#1]
Good job! It'd be handy if this project had its own package in the NuGet repository. Kudos for the code, though!

**Comment by sitebro** [comment]
@9DigitNumber It's done. 
Install-Package Avo.AspNet.Identity.MongoDB

**Comment by 9DigitNumber** [comment]
Absolutely. Thank you!

**Comment by sitebro** [comment]
I aim to update the package whenever the MongoDB driver is updated, seeing as the ASP.NET will be prioritising Identity 3.x going forward.

More importantly, I hope the developer community can be part of this project so it doesn't get abandoned like the others have.
